// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKRabr1pFjlmmaTgKrS1nR3UUh8WVJIIc',
    appId: '1:977343267818:android:df5084f88db13865e3a893',
    messagingSenderId: '977343267818',
    projectId: 'shadow-connect-fce91',
    databaseURL: 'https://shadow-connect-fce91-default-rtdb.firebaseio.com',
    storageBucket: 'shadow-connect-fce91.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWK047MglHxEIn6bf3VJUnwJgCuubeWOU',
    appId: '1:977343267818:web:d86fd04f41412e4ae3a893',
    messagingSenderId: '977343267818',
    projectId: 'shadow-connect-fce91',
    authDomain: 'shadow-connect-fce91.firebaseapp.com',
    databaseURL: 'https://shadow-connect-fce91-default-rtdb.firebaseio.com',
    storageBucket: 'shadow-connect-fce91.firebasestorage.app',
  );

}